import {
  LayoutDashboard,
  ShoppingBag,
  Package,
  Boxes,
  ReceiptText,
  Users,
  Truck,
  ShoppingCart,
  Wallet,
  ChartNoAxesCombined,
  UserRoundCog,
  Settings,
  ShieldCheck,
} from 'lucide-react';
export const navigation = [
  {
    label: 'Overview',
    path: '/',
    icon: LayoutDashboard,
    roles: ['admin', 'manager'],
    group: 'WORKSPACE',
  },
  {
    label: 'Point of sale',
    path: '/pos',
    icon: ShoppingBag,
    roles: ['admin', 'manager', 'cashier'],
    group: 'WORKSPACE',
  },
  {
    label: 'Transactions',
    path: '/sales',
    icon: ReceiptText,
    roles: ['admin', 'manager', 'cashier'],
    group: 'WORKSPACE',
  },
  {
    label: 'Products',
    path: '/products',
    icon: Package,
    roles: ['admin', 'manager', 'inventory'],
    group: 'MANAGEMENT',
  },
  {
    label: 'Inventory',
    path: '/inventory',
    icon: Boxes,
    roles: ['admin', 'manager', 'inventory'],
    group: 'MANAGEMENT',
  },
  {
    label: 'Customers',
    path: '/customers',
    icon: Users,
    roles: ['admin', 'manager', 'cashier'],
    group: 'MANAGEMENT',
  },
  {
    label: 'Suppliers',
    path: '/suppliers',
    icon: Truck,
    roles: ['admin', 'manager', 'inventory'],
    group: 'MANAGEMENT',
  },
  {
    label: 'Purchases',
    path: '/purchases',
    icon: ShoppingCart,
    roles: ['admin', 'manager', 'inventory'],
    group: 'MANAGEMENT',
  },
  {
    label: 'Expenses',
    path: '/expenses',
    icon: Wallet,
    roles: ['admin', 'manager'],
    group: 'MANAGEMENT',
  },
  {
    label: 'Reports',
    path: '/reports',
    icon: ChartNoAxesCombined,
    roles: ['admin', 'manager'],
    group: 'INSIGHTS & ADMIN',
  },
  {
    label: 'Team members',
    path: '/team',
    icon: UserRoundCog,
    roles: ['admin'],
    group: 'INSIGHTS & ADMIN',
  },
  {
    label: 'Audit trail',
    path: '/audit',
    icon: ShieldCheck,
    roles: ['admin'],
    group: 'INSIGHTS & ADMIN',
  },
  {
    label: 'Settings',
    path: '/settings',
    icon: Settings,
    roles: ['admin'],
    group: 'INSIGHTS & ADMIN',
  },
];
